//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookHub.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.UserBooks = new HashSet<UserBook>();
            this.UserFavoriteBooks = new HashSet<UserFavoriteBook>();
        }
    
        public int BookID { get; set; }
        public int GenreID { get; set; }
        public int CountryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Poster { get; set; }
        public System.DateTime AddDate { get; set; }
        public int TranslateStatusID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual TranslateStatu TranslateStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserBook> UserBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFavoriteBook> UserFavoriteBooks { get; set; }
    }
}
